# fly.toml app configuration file generated for strongmind-pizza-server on 2023-05-01T22:11:44-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "strongmind-pizza-server"
primary_region = "lax"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"
